### POST users
POST http://localhost:3000/users
Content-Type: application/json

{
  "name": "Admin",
  "email": "a@d.com",
  "password": "admin"
}


### Activate
PATCH http://localhost:3000/users/3/activate
Content-Type: application/json

{
  "activated": true
}

### Login
POST http://localhost:3000/login
Content-Type: application/json

{
  "email": "a@d.com",
  "password": "admin"
}

### GET a user
GET http://localhost:3000/users/2
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MywibmFtZSI6IkFkbWluIiwicm9sZSI6ImFkbWluIiwiaWF0IjoxNzM0OTExMTkyfQ.j0G-PySeFBpV2zZiCBdZfvAtSCvJPW8ZD3IdMZqHcYo

### GET all users
GET http://localhost:3000/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MywibmFtZSI6IkFkbWluIiwicm9sZSI6ImFkbWluIiwiaWF0IjoxNzM5NzIxMjk0fQ.-bioxucOelNv1qFYLST6sUxmMUckUS5UpS5BlNqqznU


### PATCH a user
PATCH http://localhost:3000/users/1
Content-Type: application/json

{
  "password": "Jane Doe"
}

### DELETE a user
DELETE http://localhost:3000/users/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MywibmFtZSI6IkFkbWluIiwicm9sZSI6ImFkbWluIiwiaWF0IjoxNzM0OTExMTkyfQ.j0G-PySeFBpV2zZiCBdZfvAtSCvJPW8ZD3IdMZqHcYo
